#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  2 13:12:59 2017

@author: heisenberg
"""

"""
Face detection using OpenCV and Python 2.7. Computer Vision 101
The concept used and impleted is done based on haarcascade.
"""

import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier('/home/heisenberg/OpenCV/opencv-3.1.0/data/haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('/home/heisenberg/OpenCV/opencv-3.1.0/data/haarcascades/haarcascade_eye.xml')

img = cv2.imread('face_training.jpg')
#print img
#cv2.imshow('img',img)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv2.imwrite('img.jpg',img)
#cv2.imshow('img',img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
